version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
  reviewers:
  - gsuquet
  assignees:
  - gsuquet

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  reviewers:
  - gsuquet
  assignees:
  - gsuquet
