name: Code integration
on:
  pull_request:
    types: [opened, synchronize, edited]
    branches:
    - main

jobs:
  label:
    uses: ./.github/workflows/labeler.yml

  check_pr_name:
    if: ${{ github.actor != 'dependabot[bot]'  && github.actor != 'allcontributors[bot]' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: |
        npm install commitlint-config-gitmoji commitlint
        echo "module.exports = {extends: ['gitmoji']};" > ./commitlint.config.js
    - name: Run PR name linter
      uses: JulienKode/pull-request-name-linter-action@v0.5.0

  dependency-review:
    uses: ./.github/workflows/dependencies.yml
    with:
      severity: high
